package:
  name: germline
  version: 1.5.3

source:
  fn: germline-1-5-3.tar.gz
  url: http://gusevlab.org/projects/germline/release/germline-1-5-3.tar.gz

requirements:
  build:
    - {{ compiler('cxx') }}  

test:
  commands:
    - germline -h

about:
  home: http://gusevlab.org/projects/germline/
  license: Apache License
  summary: GERMLINE is an algorithm for inferring long shared segments of Identity by Descent (IBD) between
    pairs of individuals in a large population. It takes as input haplotype marker data for individuals
    and generates a list of all shared segments. GERMLINE was developed in Itsik Pe'er's Lab at Columbia University

extra:
  identifiers:
    - doi:10.1101/gr.081398.108
